name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir build; cd build && cmake ..
    - name: ls (to debug the workflow)
      run: ls
    - name: make
      run: make
    - name: make test
      run: make test
